import type { SocialUser } from "./types";

// 42 users covering the travel + creative content scenes the trained model
// was built around. Avatars use DiceBear's deterministic API (no auth, free,
// SSR-safe). Banners use picsum with seeds.
const RAW: Omit<SocialUser, "avatarSeed" | "bannerSeed">[] = [
  { id: "u_satvik",  handle: "satvik",        name: "Satvik Adyanthaya",  bio: "Building Notecount. Travel + film photography. Mostly mountains.",                followers: 12_400, following: 312,  postCount: 86, joinedAt: "2024-09-12T09:00:00Z", verified: true, pronouns: "he/him", location: "New York, NY", link: "notecount.ai" },
  { id: "u_demo",    handle: "demo",          name: "Demo Creator",       bio: "A demo account. Use this to test the feed.",                                       followers: 142,    following: 48,   postCount: 12, joinedAt: "2025-12-04T12:00:00Z" },
  { id: "u_mira",    handle: "mira.fog",      name: "Mira Halloran",      bio: "fog → film → archive. Slow travel, slower mornings.",                              followers: 48_220, following: 184,  postCount: 412, joinedAt: "2023-04-18T07:30:00Z", verified: true, pronouns: "she/her", location: "Reykjavík" },
  { id: "u_kojiro",  handle: "kojiro.frame",  name: "Kojiro Tanaka",      bio: "Cinematic landscapes from Hokkaido and beyond.",                                   followers: 71_980, following: 92,   postCount: 524, joinedAt: "2022-11-01T03:14:00Z", verified: true, location: "Sapporo" },
  { id: "u_iris",    handle: "iris.atlas",    name: "Iris Vega",          bio: "Geographer, slow travel apologist, occasional poet.",                              followers: 9_120,  following: 230,  postCount: 188, joinedAt: "2024-02-20T10:00:00Z", pronouns: "she/her", location: "Lisbon" },
  { id: "u_dele",    handle: "dele.runs",     name: "Dele Akande",        bio: "Trail runs + travel logs. r/travel regular.",                                      followers: 5_430,  following: 410,  postCount: 96, joinedAt: "2024-08-09T16:20:00Z", location: "Lagos" },
  { id: "u_sun",     handle: "sun.kim",       name: "Sun-min Kim",        bio: "Coastal everything. Tides as a measure of time.",                                  followers: 22_100, following: 67,   postCount: 281, joinedAt: "2023-07-14T01:11:00Z", verified: true, pronouns: "they/them", location: "Busan" },
  { id: "u_aria",    handle: "aria.lens",     name: "Aria Belmonte",      bio: "Portra 400 only. Rooftops, reflections, rain.",                                    followers: 33_770, following: 142,  postCount: 308, joinedAt: "2023-01-30T18:00:00Z", pronouns: "she/her", location: "Milan" },
  { id: "u_leon",    handle: "leon.pkr",      name: "Leon Park",          bio: "Architect by day, night-walker by everything else.",                               followers: 6_840,  following: 209,  postCount: 142, joinedAt: "2024-11-22T22:00:00Z", location: "Seoul" },
  { id: "u_zoe",     handle: "zoe.adventure", name: "Zoe Marsh",          bio: "I write about the trips I don't take seriously.",                                  followers: 18_320, following: 188,  postCount: 264, joinedAt: "2023-09-03T13:45:00Z", pronouns: "she/her", location: "Wellington" },
  { id: "u_finn",    handle: "finn.alpine",   name: "Finn Lassen",        bio: "Alpinist. Cold lakes, colder hands.",                                              followers: 14_600, following: 56,   postCount: 173, joinedAt: "2023-12-12T09:00:00Z", location: "Innsbruck" },
  { id: "u_amalia",  handle: "amalia.color",  name: "Amalia Cruz",        bio: "Colorist + traveler. Pantone is a love language.",                                  followers: 7_980,  following: 410,  postCount: 121, joinedAt: "2024-05-19T11:30:00Z", pronouns: "she/her", location: "Mexico City" },
  { id: "u_omar",    handle: "omar.edits",    name: "Omar Hadid",         bio: "Editor for hire. Mostly desert, occasionally city.",                               followers: 11_410, following: 73,   postCount: 207, joinedAt: "2023-06-04T08:00:00Z", location: "Marrakech" },
  { id: "u_thalia",  handle: "thalia.tides",  name: "Thalia Okafor",      bio: "Surf + soft light. Notes from the coast.",                                         followers: 16_200, following: 98,   postCount: 254, joinedAt: "2023-03-15T05:55:00Z", verified: true, pronouns: "she/her", location: "Lagos" },
  { id: "u_ravi",    handle: "ravi.pathway",  name: "Ravi Menon",         bio: "Backpacker, writer, recovering optimist.",                                         followers: 9_840,  following: 320,  postCount: 188, joinedAt: "2024-01-08T17:30:00Z", location: "Bangalore" },
  { id: "u_juno",    handle: "juno.minimal",  name: "Juno Park",          bio: "Less but louder.",                                                                  followers: 21_620, following: 41,   postCount: 197, joinedAt: "2022-10-04T03:00:00Z", verified: true, pronouns: "she/her" },
  { id: "u_hugo",    handle: "hugo.pages",    name: "Hugo Lévesque",      bio: "Notebooks > maps. Long walks, longer essays.",                                      followers: 4_310,  following: 184,  postCount: 312, joinedAt: "2024-03-28T20:00:00Z", location: "Montréal" },
  { id: "u_freya",   handle: "freya.north",   name: "Freya Lindberg",     bio: "Polar light. Cold-weather kit nerd.",                                              followers: 13_760, following: 73,   postCount: 142, joinedAt: "2023-11-17T07:15:00Z", pronouns: "she/her", location: "Tromsø" },
  { id: "u_caleb",   handle: "caleb.maps",    name: "Caleb Whitlow",      bio: "Cartography hobbyist. Posting routes I want to walk.",                              followers: 3_120,  following: 88,   postCount: 64, joinedAt: "2025-02-12T10:00:00Z", location: "Boulder" },
  { id: "u_noor",    handle: "noor.studio",   name: "Noor Rahimi",        bio: "Studio art + studio coffee. Both warm.",                                            followers: 8_910,  following: 230,  postCount: 156, joinedAt: "2024-04-22T11:00:00Z", pronouns: "she/her", location: "Tehran" },
  { id: "u_eli",     handle: "eli.lake",      name: "Eli Kowalski",       bio: "Lake guy.",                                                                          followers: 17_230, following: 12,   postCount: 421, joinedAt: "2022-06-10T08:00:00Z", verified: true, location: "Wrocław" },
  { id: "u_yuna",    handle: "yuna.kr",       name: "Yuna Choi",          bio: "City pop, soft rain, and dim sum.",                                                followers: 26_400, following: 184,  postCount: 199, joinedAt: "2023-08-04T02:30:00Z", pronouns: "she/her" },
  { id: "u_arjun",   handle: "arjun.train",   name: "Arjun Kapoor",       bio: "Trains > planes. Notes from Indian Railways and beyond.",                          followers: 12_990, following: 76,   postCount: 232, joinedAt: "2023-02-18T19:00:00Z", location: "Mumbai" },
  { id: "u_lena",    handle: "lena.print",    name: "Lena Bauer",         bio: "Risograph + travel zines.",                                                         followers: 5_810,  following: 312,  postCount: 88, joinedAt: "2024-07-09T13:00:00Z", pronouns: "she/her", location: "Berlin" },
  { id: "u_marcus",  handle: "marcus.hike",   name: "Marcus Olin",        bio: "PCT 2024. AT 2026 (probably).",                                                     followers: 6_240,  following: 410,  postCount: 142, joinedAt: "2024-06-01T07:00:00Z", location: "Portland, OR" },
  { id: "u_sasha",   handle: "sasha.frames",  name: "Sasha Vetrov",       bio: "Streets, neon, the occasional cat.",                                                followers: 19_420, following: 142,  postCount: 287, joinedAt: "2023-05-26T22:30:00Z", pronouns: "they/them", location: "Tbilisi" },
  { id: "u_pippa",   handle: "pippa.coast",   name: "Pippa Carmichael",   bio: "Cornish coastal paths and pints.",                                                  followers: 8_140,  following: 64,   postCount: 213, joinedAt: "2023-10-14T05:30:00Z", location: "Falmouth" },
  { id: "u_taro",    handle: "taro.flora",    name: "Taro Ishikawa",      bio: "Botanical illustrator. Plant-forward travel.",                                      followers: 11_080, following: 50,   postCount: 167, joinedAt: "2024-01-29T09:00:00Z", pronouns: "he/him", location: "Kyoto" },
  { id: "u_rosa",    handle: "rosa.ferry",    name: "Rosa Petrović",       bio: "Adriatic ferries, pasta, and patience.",                                            followers: 7_320,  following: 188,  postCount: 144, joinedAt: "2024-03-03T15:00:00Z", pronouns: "she/her", location: "Split" },
  { id: "u_kabir",   handle: "kabir.delhi",   name: "Kabir Singh",        bio: "Delhi-based. Festival photos and food alleys.",                                     followers: 14_710, following: 230,  postCount: 198, joinedAt: "2023-04-09T18:30:00Z", verified: true, location: "Delhi" },
  { id: "u_anya",    handle: "anya.snow",     name: "Anya Volkova",       bio: "Avalanche tech + powder days.",                                                     followers: 9_640,  following: 73,   postCount: 121, joinedAt: "2024-02-14T11:11:00Z", pronouns: "she/her", location: "Chamonix" },
  { id: "u_idris",   handle: "idris.delta",   name: "Idris Boateng",      bio: "Delta sunsets, market stalls, tilapia.",                                            followers: 5_430,  following: 64,   postCount: 88, joinedAt: "2024-09-30T20:00:00Z", location: "Accra" },
  { id: "u_vega",    handle: "vega.night",    name: "Vega Salinas",       bio: "Astrophotographer. Posting from above the inversion.",                              followers: 22_820, following: 12,   postCount: 142, joinedAt: "2022-08-02T03:00:00Z", verified: true, pronouns: "she/her", location: "Atacama" },
  { id: "u_ben",     handle: "ben.qa",        name: "Ben Marchetti",      bio: "Asks the obvious questions. Travel forum poweruser.",                                followers: 1_220,  following: 312,  postCount: 308, joinedAt: "2024-10-12T17:00:00Z", location: "Boston" },
  { id: "u_lila",    handle: "lila.sketch",   name: "Lila Aoki",          bio: "Travel sketchbooks, daily.",                                                        followers: 17_660, following: 142,  postCount: 432, joinedAt: "2022-12-18T08:00:00Z", verified: true, pronouns: "she/her", location: "Osaka" },
  { id: "u_tom",     handle: "tom.budget",    name: "Tom Gilroy",         bio: "How to do anything for under €100.",                                                followers: 4_900,  following: 92,   postCount: 156, joinedAt: "2024-05-04T13:30:00Z", location: "Dublin" },
  { id: "u_seo",     handle: "seo.cafe",      name: "Seo-yeon Park",      bio: "Café-hopping is the trip.",                                                          followers: 13_400, following: 230,  postCount: 211, joinedAt: "2023-09-21T11:00:00Z", pronouns: "she/her", location: "Seoul" },
  { id: "u_nico",    handle: "nico.alpine",   name: "Nico Bertoli",       bio: "Dolomites resident. Vie ferrate weekends.",                                         followers: 11_220, following: 76,   postCount: 198, joinedAt: "2023-06-28T05:30:00Z", location: "Cortina d'Ampezzo" },
  { id: "u_eleni",   handle: "eleni.aegean",  name: "Eleni Papadakis",    bio: "Greek islands, slow ferries.",                                                       followers: 9_140,  following: 142,  postCount: 132, joinedAt: "2024-04-04T16:00:00Z", pronouns: "she/her", location: "Naxos" },
  { id: "u_jules",   handle: "jules.atlas",   name: "Jules Renaud",       bio: "Atlas mountains hiker, occasional chef.",                                           followers: 7_810,  following: 64,   postCount: 144, joinedAt: "2023-11-08T07:00:00Z", location: "Imlil" },
  { id: "u_priya",   handle: "priya.docs",    name: "Priya Ramaswamy",    bio: "Documentary photog. Long projects only.",                                            followers: 28_940, following: 12,   postCount: 86, joinedAt: "2022-04-12T10:00:00Z", verified: true, pronouns: "she/her", location: "Chennai" },
  { id: "u_gus",     handle: "gus.coast",     name: "Gus Carlton",        bio: "California coast caretaker.",                                                       followers: 12_330, following: 230,  postCount: 254, joinedAt: "2023-07-17T19:00:00Z", location: "Santa Cruz" },
];

export const SEED_USERS: SocialUser[] = RAW.map((u) => ({
  ...u,
  avatarSeed: u.handle,
  bannerSeed: u.handle + "-banner",
}));

export function avatarUrl(seed: string): string {
  return `https://api.dicebear.com/9.x/notionists-neutral/svg?seed=${encodeURIComponent(seed)}&backgroundType=gradientLinear`;
}
export function bannerUrl(seed: string): string {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/1200/300`;
}
